version: 1
runtime: python27
api_version: 1
threadsafe: true
application: ks-guestbook-demo

libraries:
- name: webapp2
  version: latest

handlers:
- url: /favicon.ico
  static_files: ico/carbunkl.gif
  mime_type: image/gif
  upload: ico/carbunkl.gif

- url: /.*
  script: guestbook.app

